Remove 3.14 from windows builds
Install maturin
D:\a\_temp\6a1ed005-50a2-456b-87ce-f912cd01e67e\maturin.exe build --target x86_64-pc-windows-msvc --release --out dist/ --interpreter 3.9 3.10 3.11 3.12 3.13 3.14
🔗 Found pyo3 bindings
💥 maturin failed
  Caused by: Interpreters ["CPython 3.14"] were found in maturin's bundled sysconfig, but compiling for Windows without an interpreter requires PyO3's `generate-import-lib` feature
Error: The process 'D:\a\_temp\6a1ed005-50a2-456b-87ce-f912cd01e67e\maturin.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\messense\maturin-action\v1\dist\index.js:1823:25)
    at ExecState.CheckComplete (D:\a\_actions\messense\maturin-action\v1\dist\index.js:1806:18)
    at ChildProcess.<anonymous> (D:\a\_actions\messense\maturin-action\v1\dist\index.js:1700:27)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
27s
Run messense/maturin-action@v1
Found maturin version requirement maturin>=1,<2 specified in pyproject.toml
Found maturin release from manifest: v1.9.6
Install Rust target
Install maturin
D:\a\_temp\6a1ed005-50a2-456b-87ce-f912cd01e67e\maturin.exe build --target x86_64-pc-windows-msvc --release --out dist/ --interpreter 3.9 3.10 3.11 3.12 3.13 3.14
🔗 Found pyo3 bindings
💥 maturin failed
  Caused by: Interpreters ["CPython 3.14"] were found in maturin's bundled sysconfig, but compiling for Windows without an interpreter requires PyO3's `generate-import-lib` feature
Error: The process 'D:\a\_temp\6a1ed005-50a2-456b-87ce-f912cd01e67e\maturin.exe' failed with exit code 1
    at ExecState._setResult (D:\a\_actions\messense\maturin-action\v1\dist\index.js:1823:25)
    at ExecState.CheckComplete (D:\a\_actions\messense\maturin-action\v1\dist\index.js:1806:18)
    at ChildProcess.<anonymous> (D:\a\_actions\messense\maturin-action\v1\dist\index.js:1700:27)
    at ChildProcess.emit (node:events:524:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
Error: The process 'D:\a\_temp\6a1ed005-50a2-456b-87ce-f912cd01e67e\maturin.exe' failed with exit code 1
0s